[workspace]
resolver = "2"
members = [
    "vorpal-core",
    "vorpal-ui",
    "vorpal-wasm",
    "vorpal-wasm-builtins",
    "vorpal-image",
    "vorpal-widgets",
    "examples/fluidsim",
    "examples/particle-in-a-box",
]
